slide1path = "./slide1.png"
slide1output = "./wetter-slide1.png"
slide2path = "./slide2.png"
slide2output = "./wetter-slide2.png"
gifoutput = "./wetter.gif"
fontpath = "./EuropeanTeletextNuevo.ttf"
api_key="yourkey"
